#' Annotate differentially expressed genes using biomaRt
#'
#' This function uses the `biomaRt` package to fetch a user-defined list of attributes for a list of dataframes containing differentially expressed genes. Intended to be run directly after `FindSubpopulationMarkers()`.
#' @import biomaRt
#' @param marker.genes The dataframe of marker genes generated by `FindSubpopulationMarkers()`
#' @param species The species of the cells being analyzed. Defaults to "human", but also supports "mouse".
#' @param desired.annos The vector containing the annotations you'd like to retrieve for each gene.

AnnotateMarkerGenes <- function(marker.genes = NULL,
                                species = "human",
                                desired.annos = NULL) {
  # check inputs
  if (is.null(marker.genes)) { stop("Please supply a list of dataframes containing marker genes.") }
  if (is.null(desired.attrs)) { stop("Please supply a vector of annotations you'd like to generate.") }
  # run function
  if (species == "human") {
    mart <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")
  } else if (species == "mouse") {
    mart <- useMart("ensembl", dataset = "mmusculus_gene_ensembl")
  }
  genes <- marker.genes$gene
  if (species == "human") {
    annos <- getBM(attributes = c("hgnc_symbol", desired.annos),
                   mart = mart,
                   filters = "hgnc_symbol",
                   values = genes)
  } else if (species == "mouse") {
    annos <- getBM(attributes = desired.annos,
                   mart = mart,
                   filters = "mgi_symbol",
                   values = genes)
  }

  for (i in seq(unique(marker.genes$cluster))) {
    clust_df <- marker.genes[marker.genes$cluster == unique(marker.genes$cluster)[i], ]
    genes <- clust_df$gene
    annos <- getBM(attributes = c("hgnc_symbol", desired.annos),
                   mart = mart,
                   filters = "hgnc_symbol",
                   values = genes)
  }

  return(anno_genes)
}
