#' Annotate differentially expressed genes using biomaRt
#'
#' This function uses the `biomaRt` package to fetch a user-defined list of attributes for a list of dataframes containing differentially expressed genes. Intended to be run directly after `FindSubpopulationMarkers()`.
#' @import biomaRt
#' @param marker.gene.list The list of marker gene dataframes generated by `FindSubpopulationMarkers()`
#' @param species The species of the cells being analyzed. Defaults to human, but also supports mouse.
#' @param desired.annos The vector containing the annotations you'd like to retrieve for each gene.

AnnotateMarkerGenes <- function(marker.gene.list = NULL,
                                species = "human",
                                desired.annos = NULL) {
  # check inputs
  if (is.null(marker.gene.list)) { stop("Please supply a list of dataframes containing marker genes.") }
  if (is.null(desired.attrs)) { stop("Please supply a vector of annotations you'd like to generate.") }
  # run function
  anno_gene_list <- list()
  if (species == "human") {
    mart <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")
  } else if (species == "mouse") {
    mart <- useMart("ensembl", dataset = "mmusculus_gene_ensembl")
  }
  for (i in seq(marker.gene.list)) {
    marker_df <- marker.gene.list[[i]]
    genes <- rownames(marker_df)
    if (species == "human") {
      annos <- getBM(attributes = desired.annos,
                     mart = mart,
                     filters = "hgnc_symbol",
                     values = genes)
    } else if (species == "mouse") {
      annos <- getBM(attributes = desired.annos,
                     mart = mart,
                     filters = "mgi_symbol",
                     values = genes)
    } else { stop("This function currently only supports human or mouse annotations.") }

  }
  return(anno_gene_list)
}
